import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer.jsx";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // sesuaikan kebutuhan
  variable: '--font-poppins',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <Navbar />
        <div
          className=""
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
